/* Downloads the Google Fonts the game uses and emits a self-contained CSS
   file with the woff2 payloads inlined as base64 data URIs.
   The app must work with no network at all, so nothing may stay remote.
   All four families are SIL Open Font Licence 1.1, which permits bundling
   and redistribution; see mobile/www/fonts/OFL.txt. */
import { writeFile, mkdir } from 'node:fs/promises';

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const FAMILIES = [
  { spec: 'Press+Start+2P', name: 'Press Start 2P' },
  { spec: 'VT323',          name: 'VT323' },
  { spec: 'Space+Mono',     name: 'Space Mono' },
  { spec: 'Inter:wght@400;600', name: 'Inter' }
];

// keep only the subsets that cover the characters the game actually uses:
// basic latin, latin-ext, and general punctuation (em dash, curly quotes, arrows)
function wantedSubset(comment) {
  return comment === 'latin' || comment === 'latin-ext';
}

async function get(url, binary = false) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} for ${url}`);
  return binary ? Buffer.from(await res.arrayBuffer()) : res.text();
}

let out = `/* Bundled offline. Google Fonts, SIL Open Font Licence 1.1.
   Generated by mobile/tools/fetch-fonts.mjs — do not edit by hand. */\n`;
let total = 0;

for (const fam of FAMILIES) {
  const css = await get(`https://fonts.googleapis.com/css2?family=${fam.spec}&display=swap`);
  // split into /* subset */ + @font-face pairs
  const blocks = css.split('/*').slice(1);
  for (const raw of blocks) {
    const comment = raw.slice(0, raw.indexOf('*/')).trim();
    if (!wantedSubset(comment)) continue;
    const face = raw.slice(raw.indexOf('*/') + 2);
    const urlM = face.match(/url\((https:[^)]+\.woff2)\)/);
    const weightM = face.match(/font-weight:\s*(\d+)/);
    if (!urlM) continue;
    const buf = await get(urlM[1], true);
    total += buf.length;
    const b64 = buf.toString('base64');
    out += `@font-face{font-family:'${fam.name}';font-style:normal;font-weight:${weightM ? weightM[1] : 400};font-display:block;`
         + `src:url(data:font/woff2;base64,${b64}) format('woff2');}\n`;
    console.log(`  ${fam.name} ${comment} w${weightM ? weightM[1] : 400}  ${(buf.length/1024).toFixed(1)} KB`);
  }
}

await mkdir(new URL('../www/fonts/', import.meta.url), { recursive: true });
await writeFile(new URL('../www/fonts/fonts.css', import.meta.url), out);
console.log(`\ntotal woff2 payload: ${(total/1024).toFixed(1)} KB -> www/fonts/fonts.css`);
